---
- name: restart nginx
  command: nginx -s reload
  sudo: yes
  tags:
    - needs_sudo

- name: restart php
  command: "{{item}}"
  with_items:
    - launchctl unload -w ~/Library/LaunchAgents/homebrew.mxcl.php55.plist
    - launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php55.plist

- name: rehash rbenv
  command: rbenv rehash

- name: regenerate ssh config
  assemble: src=/Users/{{ ansible_user_id }}/.ssh/config.d dest=/Users/{{ ansible_user_id }}/.ssh/config backup=yes
